### ISSUE TITLE
_cma\_rked_ *cma\*rked*  转义失效

### ISSUE THREAD

**Issue by Jiang-Xuan** [Jiang-Xuan/cmarked#1]
## 在单下划线或者是单星号中转义单下划线或单星号会导致转义失效

    marked('_cma\_rked_')
    // 输出
    "<p>_mark<em>ed</em></p>"
    marked('*cma\*rked*')
    // 输出
    "<p><em>mark</em>ed*</p>"

**Comment by osoc** [comment]
你好，看到你在marked.js那边提交的一些问题，诚意邀请你一起研究marked.js的代码。
项目介绍在www.osoc.org/A036.html
